{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "imgproxy-app.namespace" . }}    
  name: {{ include "imgproxy-app.serviceAccountName" . }}
  labels:
    {{- include "imgproxy-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
