{{- if .Values.persistence.enabled -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ include "datawise-base-app.namespace" . }}
  name: {{ include "datawise-base-app.fullname" . }}-{{ .Values.persistence.name }}
  labels:
    {{- include "datawise-base-app.labels" . | nindent 4 }}
spec:
  accessModes: [ {{ .Values.persistence.accessMode }} ]
  resources:
    requests:
      storage: "{{ .Values.persistence.size }}"
  storageClassName: {{ .Values.persistence.storageClass }}
{{- end }}
