apiVersion: v1
kind: Service
metadata:
  namespace: {{ include "datawise-base-app.namespace" . }}    
  name: {{ include "datawise-base-app.fullname" . }}
  labels:
    {{- include "datawise-base-app.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.app.port }}
      protocol: TCP
      name: appport
  selector:
    {{- include "datawise-base-app.selectorLabels" . | nindent 4 }}
