{{- if .Values.persistence.enabled -}}
{{- if eq .Values.persistence.storageClassName "nfs" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "datawise-base-app.fullname" . }}-{{ .Values.persistence.name }}
spec:
  capacity:
    storage: "{{ .Values.persistence.size }}"
  volumeMode: Filesystem
  accessModes: [ {{ .Values.persistence.accessMode }} ]
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.persistence.storageClass }}
  mountOptions: {{ .Values.persistence.nfs.options }}
  nfs:
    path: /{{ .Values.persistence.nfs.export }}
    server: {{ .Values.persistence.nfs.server }}
{{- end }}
{{- end }}
