{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ include "datawise-base-app.namespace" . }}    
  name: {{ include "datawise-base-app.serviceAccountName" . }}
  labels:
    {{- include "datawise-base-app.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
